script tweaks

diff --git a/package/batocera/core/batocera-desktopapps/scripts/batocera-config-vita3k b/package/batocera/core/batocera-desktopapps/scripts/batocera-config-vita3k
--- a/package/batocera/core/batocera-desktopapps/scripts/batocera-config-vita3k
+++ b/package/batocera/core/batocera-desktopapps/scripts/batocera-config-vita3k
@@ -13,4 +13,14 @@ export XDG_CACHE_HOME="/userdata/system/cache"
 export XDG_DATA_HOME="/userdata/saves"
 
 # Now run the emulator
-/usr/bin/vita3k/Vita3K
+if [[ -x /usr/bin/vita3k/Vita3K ]]; then
+    echo "Starting Vita3K..."
+    USER=root \
+    QT_PLUGIN_PATH=/usr/lib/qt6/plugins \
+    QT_QPA_PLATFORM=xcb \
+    QT_XCB_NO_XI2=1 \
+    /usr/bin/vita3k/Vita3K
+else
+    echo "System not found."
+    exit 1
+fi
