updates before rebuild

diff --git a/package/batocera/emulators/wine/batocera-wine/batocera-wine b/package/batocera/emulators/wine/batocera-wine/batocera-wine
--- a/package/batocera/emulators/wine/batocera-wine/batocera-wine
+++ b/package/batocera/emulators/wine/batocera-wine/batocera-wine
@@ -61,7 +61,7 @@ usage() {
     echo "${1} windows play             <game>.wtgz"            >&2
     echo "${1} windows install          <game>.iso"             >&2
     echo "${1} windows install          <game>.exe"             >&2
-    echo "${1} windows tricks           <game>.wine directplay" >&2
+    echo "${1} windows tricks         <game>.wine directplay" >&2
     echo "${1} windows wine2squashfs <game.wine>"            >&2
     echo "${1} windows wine2winetgz  <game.wine>"            >&2
 }
@@ -154,7 +154,7 @@ wine_options() {
     test "${DXVK_RESET_CACHE}" = 1 && DXVK_STATE_CACHE=reset
 
     export NTFS_MODE=0
-    test "${WINE_NTFS}" = 0 && NTFS_MODE=1
+    test "${WINE_NTFS}" = 1 && NTFS_MODE=1
 
     export STAGING_SHARED_MEMORY=1
     export ULIMIT_SIZE=1048576
@@ -187,7 +187,7 @@ if test -e "${USER_DIR}/exe"; then
 
         case "${file}" in
 
-          "${USER_DIR}/exe/DXSETUP.exe" | "${USER_DIR}/exe/dxsetup.exe")
+        "${USER_DIR}/exe/DXSETUP.exe" | "${USER_DIR}/exe/dxsetup.exe")
             WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /silent &>/dev/null || return 1
             "${WINESERVER}" -w
             ;;
@@ -197,12 +197,12 @@ if test -e "${USER_DIR}/exe"; then
             "${WINESERVER}" -w
             ;;
 
-          "${USER_DIR}/exe/vcredist_x64_2008.exe" | "${USER_DIR}/exe/vcredist_x86_2008.exe")
+        "${USER_DIR}/exe/vcredist_x64_2008.exe" | "${USER_DIR}/exe/vcredist_x86_2008.exe")
             WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
             "${WINESERVER}" -w
             ;;
 
-          "${USER_DIR}/exe/vcredist_x64_2010.exe" | "${USER_DIR}/exe/vcredist_x86_2010.exe")
+        "${USER_DIR}/exe/vcredist_x64_2010.exe" | "${USER_DIR}/exe/vcredist_x86_2010.exe")
             WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
             "${WINESERVER}" -w
             ;;
@@ -247,7 +247,7 @@ if test -e "${USER_DIR}/exe"; then
             "${WINESERVER}" -w
             ;;
 
-          *)
+        *)
             WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" &>/dev/null
             "${WINESERVER}" -w
             ;;
@@ -324,34 +324,30 @@ dxvk_install() {
     DXVK=$(get_setting dxvk "${SYSTEM}" "${ROMGAMENAME}")
     DXVK_HUD=$(get_setting dxvk_hud "${SYSTEM}" "${ROMGAMENAME}")
 
-    if test "${DXVK_HUD}" = 1
-    then
+    if test "${DXVK_HUD}" = 1; then
         export DXVK_HUD=1
     fi
 
-    if test "${DXVK}" = 1
-    then
     mkdir -p "${WINEPREFIX}/drive_c/windows/system32" "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
-    if test -e "/userdata/system/wine/dxvk"
-    then
-        echo "Creating links on /userdata, Linux File System required !!!"
-        ln -sf "/userdata/system/wine/dxvk/x64/"{d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi64.dll} "${WINEPREFIX}/drive_c/windows/system32" || return 1
-        ln -sf "/userdata/system/wine/dxvk/x32/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi.dll} "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
+    if test "${DXVK}" = 1; then
+        if test -e "/userdata/system/wine/dxvk"; then
+            echo "Creating links using /userdata, Linux File System required !!!"
+            ln -sf "/userdata/system/wine/dxvk/x64/"{d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi64.dll} "${WINEPREFIX}/drive_c/windows/system32" || return 1
+            ln -sf "/userdata/system/wine/dxvk/x32/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi.dll} "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
+        else
+            echo "Creating links using /usr/wine/dxvk/, Linux File System required !!!"
+            ln -sf "/usr/wine/dxvk/x64/"{d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi64.dll} "${WINEPREFIX}/drive_c/windows/system32" || return 1
+            ln -sf "/usr/wine/dxvk/x32/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi.dll} "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
+        fi
     else
-        echo "Creating links on /userdata, Linux File System required !!!"
-        ln -sf "/usr/wine/dxvk/x64/"{d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi64.dll} "${WINEPREFIX}/drive_c/windows/system32" || return 1
-        ln -sf "/usr/wine/dxvk/x32/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi.dll} "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
-    fi
-    else
-        echo "Creating links on /userdata, Linux File System required !!!"
-        ln -sf "/usr/wine/${WINE_VERSION}/lib/wine/x86_64-windows/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll}   "${WINEPREFIX}/drive_c/windows/system32" || return 1
-        ln -sf "/usr/wine//${WINE_VERSION}/lib/wine/i386-windows/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll} "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
+        echo "Creating links using ${DIR}/${WINE_VERSION}, Linux File System required !!!"
+        ln -sf "/usr/wine/${WINE_VERSION}/lib/wine/x86_64-windows/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll} "${WINEPREFIX}/drive_c/windows/system32" || return 1
+        ln -sf "/usr/wine/${WINE_VERSION}/lib/wine/i386-windows/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll}   "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
     fi
 
-    if test "${DXVK}" = 1
-    then
+    if test "${DXVK}" = 1; then
         export DXVK_ASYNC=1
-        export DXVK_CONFIG_FILE="/userdata/system/wine/dxvk/dxvk.conf"
+        export DXVK_CONFIG_FILE="/userdata/system/wine/dxvk.conf"
         export WINEDLLOVERRIDES="${WINEDLLOVERRIDES};dxgi,d3d8,d3d9,d3d10core,d3d11,d3d12,d3d12core=n"
         export DXVK_STATE_CACHE_PATH="/userdata/system/cache"
     else
@@ -359,8 +355,7 @@ dxvk_install() {
         export WINEDLLOVERRIDES="${WINEDLLOVERRIDES};dxgi,d3d8,d3d9,d3d10core,d3d11,d3d12,d3d12core=b"
     fi
 
-    if test "${NVAPI}" = 1
-    then
+    if test "${NVAPI}" = 1; then
         export DXVK_ENABLE_NVAPI=1
         export WINEDLLOVERRIDES="${WINEDLLOVERRIDES};nvapi,nvapi64=n"
     else
